package org.javaboy.fileupload.dao;

import java.util.List;
import org.javaboy.fileupload.entity.ConnEntity;
import org.springframework.stereotype.Repository;

public interface ConnEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    int insert(ConnEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    ConnEntity selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    List<ConnEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    int updateByPrimaryKey(ConnEntity record);

    List<ConnEntity> selectByUid(String uid);
}