package org.javaboy.fileupload.dao;

import java.util.List;
import org.javaboy.fileupload.entity.TopicEntity;

public interface TopicEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    int deleteByPrimaryKey(int tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    int insert(TopicEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    TopicEntity selectByPrimaryKey(int tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    List<TopicEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    int updateByPrimaryKey(TopicEntity record);
}