package org.javaboy.fileupload.dao;

import java.util.List;
import org.javaboy.fileupload.entity.TopicEntity;
import org.springframework.stereotype.Repository;

public interface TopicEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    int deleteByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    int insert(TopicEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    TopicEntity selectByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    List<TopicEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    int updateByPrimaryKey(TopicEntity record);
}