package org.javaboy.fileupload.dao;

import java.util.List;
import org.javaboy.fileupload.entity.ConnEntity;

public interface ConnEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    int deleteByPrimaryKey(int cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    int insert(ConnEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    ConnEntity selectByPrimaryKey(int cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    List<ConnEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conn
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    int updateByPrimaryKey(ConnEntity record);

    List<ConnEntity> selectByUid(String uid);
}