package org.javaboy.fileupload.entity;

import java.io.Serializable;
import java.util.Date;

public class TopicEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.tid
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    private int tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.imageurl
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.tag
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.time
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.tid
     *
     * @return the value of topic.tid
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public int getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.tid
     *
     * @param tid the value for topic.tid
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public void setTid(Integer tid) {
        this.tid = tid == null ? null : tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.imageurl
     *
     * @return the value of topic.imageurl
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.imageurl
     *
     * @param imageurl the value for topic.imageurl
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.tag
     *
     * @return the value of topic.tag
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.tag
     *
     * @param tag the value for topic.tag
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.time
     *
     * @return the value of topic.time
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.time
     *
     * @param time the value for topic.time
     *
     * @mbg.generated Thu Jan 21 13:58:25 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }
}