spring:
  datasource:
    name: graduate_db
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/graduate_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "00000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port : 8082
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml