package org.javaboy.fileupload.entity;

import java.io.Serializable;

public class ConnEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conn.cid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conn.uid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conn.tid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table conn
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conn.cid
     *
     * @return the value of conn.cid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conn.cid
     *
     * @param cid the value for conn.cid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conn.uid
     *
     * @return the value of conn.uid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conn.uid
     *
     * @param uid the value for conn.uid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conn.tid
     *
     * @return the value of conn.tid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conn.tid
     *
     * @param tid the value for conn.tid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}