package org.javaboy.fileupload.entity;

import java.io.Serializable;

public class TopicEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.tid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.imageurl
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.tags
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.tid
     *
     * @return the value of topic.tid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.tid
     *
     * @param tid the value for topic.tid
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.imageurl
     *
     * @return the value of topic.imageurl
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.imageurl
     *
     * @param imageurl the value for topic.imageurl
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.tags
     *
     * @return the value of topic.tags
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.tags
     *
     * @param tags the value for topic.tags
     *
     * @mbg.generated Wed Jan 20 15:46:03 CST 2021
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }
}